server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:clinicaweb  # URL de conexão com o banco de dados H2 em memória
    driver-class-name: org.h2.Driver  # Classe do driver JDBC para o H2
    username: sa  # Usuário do banco de dados (padrão para o H2)
    password:   # Senha do banco de dados (vazio para o H2)
    initialization-mode: always
  jpa:
    show-sql: true  # Exibe as queries SQL executadas pelo Hibernate
  h2:
    console:
      enabled: true