apiVersion: v1
kind: Service
metadata:
  name: kotlin-app-service
spec:
  selector:
    app: clinicakotlin
  ports:
    - protocol: TCP
      port: 80            # Porta exposta pelo serviço
      targetPort: 8080    # Porta onde a aplicação está rodando no contêiner
  type: LoadBalancer      # Tipo de serviço
